# Generated by Django 4.2.8 on 2024-02-13 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sub_menu', models.ManyToManyField(to='uts.category', verbose_name='Sub Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Manage Menu',
            },
        ),
    ]
