# Generated by Django 4.2.8 on 2024-01-13 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('poster_image', models.ImageField(help_text='Video thumbnail image', upload_to='video_poster_image/%Y/%m/%d/', verbose_name='Poster Image')),
                ('citations', models.TextField()),
                ('trending', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uts.author', to_field='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uts.category', to_field='title')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='uts.tag')),
            ],
            options={
                'verbose_name': 'Video Metadata',
                'verbose_name_plural': 'Manage Video Metadata',
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('start_time', models.CharField(max_length=10, verbose_name='Start Time (MM.SS)')),
                ('qna_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_metadata.videometadata')),
            ],
        ),
    ]
